[project]
name = "grassbook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flask>=3.1.1",
    "humanize>=4.12.3",
    "supabase>=2.16.0",
]
